### ISSUE TITLE
BeforeInstallPromptEvent.Prompt throws exception

### ISSUE THREAD

**Issue by RonPeters** [LostBeard/SpawnDev.BlazorJS#11]
I'm trying to follow best practice to create a custom PWA install experience: https://web.dev/customize-install/

In short, this involves hooking the BeforeInstallPrompt event, caching the BeforeInstallPromptEvent, and then calling it later after presenting a custom UI.

I do something like this:

```cs
protected override async Task OnInitializedAsync()
{
    using var window = JS.Get<Window>("window");
    window.OnBeforeInstallPrompt += Window_OnBeforeInstallPrompt;
}

private BeforeInstallPromptEvent? DeferredPrompt;
void Window_OnBeforeInstallPrompt(BeforeInstallPromptEvent e)
{
    e.PreventDefault();
    DeferredPrompt = e;
    InvokeAsync(() => StateHasChanged()); // This enables the custom install button in the UI
}

// This gets called with the result of the custom dialog we present to the user
async Task HandleInstallDialog(DialogResult dialogResult)
{
    try
    {
        if (dialogResult.Cancelled)
        {
            Logger.LogInformation("User cancelled install app promo dialog");
        }
        else if (DeferredPrompt != null)
        {
            var installResult = await DeferredPrompt.Prompt; // <-- crashes here
            Logger.LogInformation($"User responded to app installation with outcome: {installResult.Outcome}");
        }
    }
    catch (Exception ex)
    {
        Logger.LogError("Error installing app", ex);
    }
}

```

Exception is a JSException with Message: 'undefined\nundefined'

...btw, I think Prompt should really be a function Prompt()

It's kind of a pain to test because Chrome disables the beforeInstallPrompt event after the crash, so if you need to force it, go to Dev Tools and enter this into the Console: `window.dispatchEvent(new Event('beforeinstallprompt'))`

**Comment by RonPeters** [comment]
I think there may be a discrepancy in Google's documentation. It says that both prompt() and userChoice return the install result, but the latest example shows a different flow: [How to add Richer Install UI](https://web.dev/patterns/web-apps/)
```
installEvent.prompt();
const result = await installEvent.userChoice;
```
Perhaps Prompt is a void now?

**Comment by LostBeard** [comment]
There was a bug in the JSObject BeforeInstallPromptEvent. Fixed now in the repo. I'll update the Nuget shortly. Thank you for finding this issue.

```cs
public Task<InstallPromptResult> Prompt() => JSRef.CallAsync<InstallPromptResult>("Prompt");
// to
public Task<InstallPromptResult> Prompt() => JSRef.CallAsync<InstallPromptResult>("prompt");
```

**Comment by LostBeard** [comment]
One thing to note. While testing I the beforeinstallprompt event code I notcied it usually fires before the Blazor app loads and therefore before we can attach Blazor event handlers. I ended up handling that by adding a bit of code into the index.html file to save the event and then pick it up in Blazor when it loads.

In a <script> tag in index.html
```js
window.addEventListener('beforeinstallprompt', function (e) {
    window.DeferredBeforeInstallPromptEvent = e;
    e.preventDefault();
});
```

Then in Blazor, likely in your OnInitializedAsync override:
```cs
var deferredPrompt = JS.Get<BeforeInstallPromptEvent?>("DeferredBeforeInstallPromptEvent");
if (deferredPrompt  != null) {
  // handle the missed event
  // ...
}
```

**Comment by LostBeard** [comment]
I tested beforeinstallprompt on Chrome Android and Chrome for Windows and both are working as expected now.

**Comment by LostBeard** [comment]
I have a working example on my test site [www.spawndev.com](https://www.spawndev.com/) (heavily in development). 

When you first go to the test site it prompts to install only once per session if not already installed. This is similar to reddit's method when used on Android. 

There is also a passive (non-modal) install button in the top right user bar that can show the install confirmation modal on user request.

I likely won't keep the per-session install modal popup. But it shows a possible use case.

**Comment by LostBeard** [comment]
SpawnDev.BlazorJS version 2.2.3 Nuget package is up with the fix.

**Comment by RonPeters** [comment]
Working like a charm now. You rock!
