### ISSUE TITLE
Task Cancellation

### ISSUE THREAD

**Issue by rachied** [LostBeard/SpawnDev.BlazorJS#2]
Hello,

First of all, thank you for making such an awesome library. I was disappointed by the lack of .NET 7 support in BlazorWorker, so I'm glad to have stumbled upon yours.

I am trying to utilize web workers to execute some long running tasks (running dynamically compiled code / unit tests), and some of them may run infinitely long. Which is why I am searching for some way to terminate tasks after a certain period of time. 

Using BlazorJS.WebWorkers I was able to offload the compilation and execution of the tests to a WebWorker, so the browser UI no longer hangs. And by chaining `WaitAsync` to the Task that is returned by the WebWorker and awaiting that, it will throw a TimeOutException when the Task exceeds the timeout that has been set. All good so far!

However, the WebWorker continues executing the Task until completion, and I'd like for a way to stop it from doing that..
I do not control all the inner workings of my test runner, so I am unable to e.g. send over a CancellationToken and check that continuously. Do you have any idea how to achieve this?

Here's a code snippet for reference:

```csharp
public async Task CompileAndRun()
{
    var code = await Editor.GetValue();
    
    _webWorker ??= await WebWorkerService.GetWebWorker();
    
    var runner = _webWorker.GetService<ITestWorker>();

    try
    {
        var result = await runner
            .RunTests(code)
            .WaitAsync(TimeSpan.FromSeconds(5));

        if (result.TestCount == 0)
        {
            await Alert("An unexpected error occurred");
            return;
        }

        if (result.FailedCount > 0)
        {
            await Alert("One or more tests failed");
        }
        else
        {
            await Alert("All tests passed, nice!");
        }
    }
    catch (TimeoutException e)
    {
        await Alert("Test suite timed out");
    }
    finally
    {
        _webWorker?.Dispose();
        _webWorker = null;
        // In case of timeout, WebWorker is still doing work at this point..
    }
}
```

**Comment by rachied** [comment]
I guess [Worker.terminate()](https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate) is what I'm looking for. I don't think we have a binding for that yet (or I didn't look in the right places)

**Comment by LostBeard** [comment]
Calling Dispose on the WebWorker calls the underlying worker's terminate method. I just tested on the [demo WebWorker page ](https://blazorjs.spawndev.com/WebWorker) and clicking the Dispose button while the worker is worker stops it and kills the worker. I'm not sure why it is not doing the same for your tests.

**Comment by rachied** [comment]
You are correct. It's my setup that was wrong. Those `await Alert()` calls invoked the JS alert, which blocked the main thread and allowed the web worker to continue on a bit past the timeout period - leading me to believe it wasn't being terminated.
