### ISSUE TITLE
blazorjs.spawndev.com WebWorker demo fails on Firefox

### ISSUE THREAD

**Issue by Martin521** [LostBeard/SpawnDev.BlazorJS#3]
The demo works for me on Chrome.
In Firefox, I get `ReferenceError: blazorWASMScriptEl is not defined`.
(Firefox 111.0.1 (64-bit) on Windows 11)

**Comment by LostBeard** [comment]
Thank you. Fixing now.

**Comment by LostBeard** [comment]
I have updated the repo, demo site, and Nuget. Thank you for the heads up. 👍

**Comment by Martin521** [comment]
Awesome. Thanks!

**Comment by Martin521** [comment]
Fyi: I created a [small demo project](https://github.com/Martin521/BoleroWebworkerDemo), demonstrating how to use SpawnDev.BlazorJS.WebWorkers from F#, together with [Bolero](https://github.com/fsbolero/Bolero), a F# adaptation of Blazor. And posted it in the F# community.

Thank you for making WebWorkers for Blazor available.
