### ISSUE TITLE
Will it support auto mode and server mode in web apps？

### ISSUE THREAD

**Issue by hhhenggg** [LostBeard/SpawnDev.BlazorJS#31]
I am looking for blazer to run JavaScript. This project is great, I need to use it in projects in auto mode，but the  web app auto mode is not yet supported. Will it be supported in the future?

**Comment by LostBeard** [comment]
SpawnDev.BlazorJS requires IJSInProcessRuntime to make synchronous calls into the Javascript environment. Server side rendering uses the default Javascript runtime, IJSRuntime, which only supports asynchronous calls to Javascript. Because of that, there is no easy way to make SpawnDev.BlazorJS work in server side rendering at this time. I cannot say it will never work with server side rendering as I do have some ideas that I may try at some point, but I do not see it happening anytime soon.

**Comment by hhhenggg** [comment]
Thank you for your reply.  I use the auto mode in blazor, which is something I need. I think many people will also need it, and I hope to use it in future projects. I will continue to monitor the progress of blazorjs, and thank you for providing excellent projects for everyone.

**Comment by LostBeard** [comment]
According to my project README.md I have tested SpawnDev.BlazorJS in ```auto``` mode and it is working. Have you tried it?

**Comment by LostBeard** [comment]
I'm sure it only works in the client project though and not in the server project.

**Comment by hhhenggg** [comment]
> According to my project README.md I have tested SpawnDev.BlazorJS in mode and it is working. Have you tried it?`auto`
I have tried the webassembly mode and it works. The server that runs first in auto mode, and the client that runs only after downloading the client code, will report the following error if the service is not registered when running on the server.
![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/45975545/fb0cf7ee-c2d2-442a-858c-7af60a437552)
![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/45975545/5e6ccc07-811c-4b05-a944-356294e2f7fa)
![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/45975545/d8772a55-318c-4a7b-a36b-c9b33c90e1a2)

**Comment by LostBeard** [comment]
That isn't very clear. So to clarify: The app ```Interactive render mode`` can be set to ```Auto (Server and WebAssembly)```and use any rendering mode for components that do not use SpawnDev.BlazorJS but components that do use SpawnDev.BlazorJS will have to be set to ```InteractiveWebAssembly``` with prerendering disabled at the component level. ```Interactivity location``` should be ```Per page/component```.

Example WasmPage.raozr:  
```cs
@page "/wasm"
@using SpawnDev.BlazorJS;
@rendermode @(new InteractiveWebAssemblyRenderMode(prerender: false))

<h1>Wasm Page</h1>

RenderMode: @(OperatingSystem.IsBrowser() ? "WebAssembly" : "Server")

@code {

    [Inject]
    BlazorJSRuntime JS { get; set; }

    protected override void OnInitialized()
    {
        JS.Set("document.title", "Hello world from wasm page!");
    }
}

```

You can even use WASM components in the server project's serer rendered pages. The below component ```WasmComponent``` can be added to server rendered pages and it will load using the WASM environment

Example WasmComponent.raoz:
```cs
@using SpawnDev.BlazorJS;
@rendermode @(new InteractiveWebAssemblyRenderMode(prerender: false))

<h1>Wasm Component</h1>

RenderMode: @(OperatingSystem.IsBrowser() ? "WebAssembly" : "Server")

@code {

    [Inject]
    BlazorJSRuntime JS { get; set; }

    protected override void OnInitialized()
    {
        JS.Set("document.title", "Hello world from wasm component!");
    }
}
```

I spend most of my time working on the WASM part of it. I created a ```Blazor Web App``` to test this out to help clarify what needs to happen to get it working (for us both.) I hope this helps.

**Comment by LostBeard** [comment]
I uploaded the ```Blazor Web App``` project I tested with. The repo is here: [BlazorJSWebAppTest](https://github.com/LostBeard/BlazorJSWebAppTest)

**Comment by hhhenggg** [comment]
Thank you, I know where the problem is and I used global auto mode. Or is it because it's running on the server。
![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/45975545/4e349700-71b6-443d-ab00-46a6bb14b5b7)

**Comment by LostBeard** [comment]
I added a new section to the project README.md [Blazor Web App compatibility
](https://github.com/LostBeard/SpawnDev.BlazorJS?tab=readme-ov-file#blazor-web-app-compatibility).

**Comment by LostBeard** [comment]
To change an existing project ```Interacticity location``` from ```Global``` to ```Per component/page``` remove ```@rendermode``` attribute from the ```Routes``` element in you ```App.razor``` page. Then the per component attribute will work in your WebAssembly pages and components. 

Change this:  
```html
<body>
    <Routes @rendermode="InteractiveAuto" />
    <script src="_framework/blazor.web.js"></script>
</body>
```
To this:  
```html
<body>
    <Routes />
    <script src="_framework/blazor.web.js"></script>
</body>
```

Then this will work in your WebAssembly components:  
```cs
@rendermode @(new InteractiveWebAssemblyRenderMode(prerender: false))
```

**Comment by LostBeard** [comment]
Related info on changing the ```rendermode``` for the entire app: [Apply a render mode to the entire app
](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#apply-a-render-mode-to-the-entire-app).

**Comment by hhhenggg** [comment]
Thank you, I know all of this. My project has a lot of content, and the first access in client mode will be slow, so I need to run it on the server side, so I can only wait for the support server to run.
