### ISSUE TITLE
Missing method: Element.prepend()

### ISSUE THREAD

**Issue by jhorv** [LostBeard/SpawnDev.BlazorJS#32]
Please add a `Prepend` method to the `Element` class corresponding with [Element.prepend()](https://developer.mozilla.org/en-US/docs/Web/API/Element/prepend)

**Comment by LostBeard** [comment]
Version 2.2.91 is now up and contains the [Element.Prepend](https://developer.mozilla.org/en-US/docs/Web/API/Element/prepend) method.
