### ISSUE TITLE
Wrong static class property value

### ISSUE THREAD

**Issue by khelifaadm** [LostBeard/SpawnDev.BlazorJS#38]
**Describe the bug**
When setting static prtoperty value,i expect to get same value in the worker

**To Reproduce**
1. Create classes:
```
public static class ConfigApp
{
    public static string DateFormat {get; set;} ="DefaultFormat";
}

public interface IService
{
    string LogConfigAppState();
}

public class Service:IService
{
    public  string LogConfigAppState()
    {
      Console.WriteLine(ConfigApp.DateFormat);
      return ConfigApp.DateFormat;
    }
}
```
2. in any page when button clicked event code:
```
private Task OnClick()
{
  ConfigApp.DateFormat ="Modified"; // <== Change value of the static class member
  if (webWorker == null) webWorker = await webWorkerService.GetWebWorker() ?? throw new ArgumentNullException(nameof(webWorker));
  var service= webWorker.GetService<IService>();
  ...
  var result = service.LogConfigAppState(); //<== here excpected "Modified" actual is "DefaultFormat"
}

```
**Expected behavior**
Result of service.LogConfigAppState excpected to be "Modified" but actual result is "DefaultFormat"

**Comment by LostBeard** [comment]
static variables are not shared between scopes, such as a WebWorker and a Window. They are essentially running as separate processes that use postMessage for inter process communication, not separate threads.... which would share static variables.

**Comment by LostBeard** [comment]
It looks like just quick example code, but your example code is trying to use an interface proxy (acquired via `var service= webWorker.GetService<IService>();`) with synchronous properties and methods which it does not support. More info here: [Supported Instance To Instance Calling Conventions](https://github.com/LostBeard/SpawnDev.BlazorJS?tab=readme-ov-file#supported-instance-to-instance-calling-conventions). 

To access properties and synchronous methods you can use the WebWorker `Run` method.

The below example sets your static property in the worker and then calls your synchronous method in the worker, returning the string value.

```cs
private async Task OnClick()
{
  if (webWorker == null) webWorker = await webWorkerService.GetWebWorker() ?? throw new ArgumentNullException(nameof(webWorker));
  ...
  await webWorker.Run(() => ConfigApp.DateFormat ="Modified"); // <== Change value of the static class member in the worker
  var result = await webWorker.Run<IService, string>((service) =>  service.LogConfigAppState()); //<== here is "DefaultFormat"
}
```

**Comment by khelifaadm** [comment]
Thanks for the response
I tried "lock statement"  to solve the problem, thinking that main thread and the worker would compete for same static resource
```
public static class ConfigApp
{
    private static object _locker = new();
    private static string _dateFormat = "DefaultFormat";

    public static string DateFormat
    {
        get
        {
            lock (_locker)
            {
            return _dateFormat;
            }
        }
        set
        {
            lock (_locker)
            {
                _dateFormat = value;
            }
        }
    }
}
```
without a positive result
But the :
` await webWorker.Set(() => ConfigApp.DateFormat, "Modified");`
solved the problem
Thank you again

**Comment by LostBeard** [comment]
lol I assume you reopened the issue in case I didn't want it closed. I'll close it now under that assumption. I don't mind if users close there own issues. Feel to reopen if needed.
