### ISSUE TITLE
IDBDatabase incorrect read mode

### ISSUE THREAD

**Issue by pavel-zhur** [LostBeard/SpawnDev.BlazorJS#41]
The `IDBDatabase.Transaction` methods haveoverloads with the `bool readWrite` parameter that is then translated like this: `readWrite ? "readwrite" : "read"`.

I think this is incorrect, the correct mode is `"readonly"` instead of `"read"`.

Location: https://github.com/LostBeard/SpawnDev.BlazorJS/blob/main/SpawnDev.BlazorJS/JSObjects/IDBDatabase.cs
Lines 97, 99, 117, 120.
IDBTransaction documentation: https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/mode

**Comment by LostBeard** [comment]
You are correct. Thank you. 👍
