### ISSUE TITLE
Wrong _frameworkPath when the location includes the index doc name

### ISSUE THREAD

**Issue by Martin521** [LostBeard/SpawnDev.BlazorJS#5]
If you include the trailing `/index.html` in the browser address (I have to do this in certain situations), the _framework and _content paths are no longer correct (they include the `/index.html`).

I guess this would need to be checked in spawndev.blazorjs.webworkers.js near line 60.

**Comment by Martin521** [comment]
Thank you for looking into it.

> What is the error(s) you are getting?
What is the address of the first _framework file that fails to load due to the wrong address?

Loading module from “http://mybucket....amazonaws.com/index.html/_content/SpawnDev.BlazorJS/SpawnDev.BlazorJS.lib.module.js” was blocked because of a disallowed MIME type (“text/html”).

> What is your index.html base href? (<base href="/" />)

Ah, that makes the difference. I don't have a base element in index.html (to be flexible regarding deployment). So base = location.href. Not sure if that is a use case you would consider covering. As mentioned, I can work around it.

**Comment by LostBeard** [comment]
Ah. I cannot fix that. That error occurs before my code runs.

By not using the base element in your index.html you are breaking some of the functionality of Blazor not limited to WebWorkers or BlazorJS. The part that WebWorkers use that is breaks is Blazor's "JS Initializers" (see references)

"JS initializers are detected as part of the build process and imported automatically in Blazor apps."
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#javascript-initializers

"Important. For URLs to resolve correctly, the app must include a <base> tag (location of <head> content) with the app base path specified in the href attribute. For more information, see Host and deploy ASP.NET Core Blazor."
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0

Related reference:

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-7.0#inject-a-script-after-blazor-starts

**Comment by LostBeard** [comment]
I deploy some of my Blazor WASM apps on AWS also. I tend to use CloudFront with my own DNS but I might be able to help if you are having an issue using when you use the base element. 

In S3, I believe you can set an index document so your index.html is used when no file specified. And you can even set a custom 404 page to also point at your index.html so it always uses your index.html.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/IndexDocumentSupport.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/CustomErrorDocSupport.html

**Comment by Martin521** [comment]
Thank you for the references. That clarifies the matter.
