### ISSUE TITLE
Incompatiblity with Microsoft.Authentication.WebAssembly.Msal Package when using WebWorkers

### ISSUE THREAD

**Issue by nantcom** [LostBeard/SpawnDev.BlazorJS#7]
First of all, thank you for all the effort you have put into this library :)

## Issue:
If the project uses `Microsoft.Authentication.WebAssembly.Msal` nuget package, an exception will be thrown at this line:

```c#
var webWorker = await workerService.GetWebWorker();
```

## Exception Detail

![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/7698652/b5192859-a006-4a4c-b571-f774af383c4c)

## Root Cause
The root cause was MSAL library was trying to read `appsettings.json` which is not available at the location specified.

![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/7698652/040a5f65-38da-41a5-9929-363f54915aab)

## Workaround

Create `appsettings.json` file at `wwwroot/_content/SpawnDev.BlazorJS.WebWorkers/appsettings.json` with empty JSON object as follows:

![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/7698652/12e103af-89e8-4e6b-8139-1a2bc4e1b0f5)

with workaround, the library functions normally.

![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/7698652/c6eaa107-3c30-45e6-aa4f-96d65cd73bf2)

**Comment by LostBeard** [comment]
@nantcom Thank you for submitting your issue. Unfortunately I cannot reproduce it. The [demo site](https://blazorjs.spawndev.com/) uses appsettings.json also. You can see that the appsettings.json is properly loaded by looking at the console output when you run the worker test. It outputs a message from appsettings.json and says what global context it is in.

Below is the message seen in the browser console after starting a worker on the demo site. "Hello from appsettings.json" is read from the appsettings.json file (see Client/Program.cs)
```
appsettings test in context DedicatedWorkerGlobalScope: Hello from appsettings.json
```

Can you share a test project that demonstrates the issue? I will take a look and do my best to figure this out.

Funny note... the issue you are reporting is actually the very first issue that was reported on this project. At that time there was an issue with my code and I fixed it. He was also using or planned to use MSAL.

**Comment by LostBeard** [comment]
I got caught up verifying that appsettigns was loading correctly with my code I partially ignored "If the project uses Microsoft.Authentication.WebAssembly.Msal nuget package ...".

I will create a test app with that included and let you know.

**Comment by LostBeard** [comment]
I created a basic test project that has the package "Microsoft.Authentication.WebAssembly.Msal". It is loading the appsettings.json correctly. At this point I need more info or an example project to help as I cannot reproduce the reported issue.

[BlazorJSMSALTest](https://github.com/LostBeard/BlazorJSMSALTest)

**Comment by nantcom** [comment]
Sorry, I missed one crucial info .🙏 As soon as I add Msal package *and* have `appsettings.json` in a project (since you need to configure MSAL) that exception will surface. If you add Msal Nuget and  _**does not have**_ `appsettings.json` - everything will work fine. But I can see your project has `appsettings.json` - so I am not sure why. Maybe it's `builder.Services.AddMsalAuthentication`

I actually lost a bit of hair (since I went to have a haircut to calm down 😂) trying to figure out why creating an empty project + adding your library works and my almost-production project doesn't. 

This is the test project I was testing.
[BlazorParallelWithMSAL.zip](https://github.com/LostBeard/SpawnDev.BlazorJS/files/11522694/BlazorParallelWithMSAL.zip)

This is me testing it :

https://github.com/LostBeard/SpawnDev.BlazorJS/assets/7698652/4af02056-4f58-447c-8278-643e0b9c941f

IMO, you don't have to fix anything and I think it is MSAL issue that needs a workaround for this specific use case.🥲

**Comment by LostBeard** [comment]
I see you are using .Net 7. I have been using .Net 8 mostly since it was released. Checking if that may be it...

**Comment by LostBeard** [comment]
You are appsettings.json is not being loaded even in the main window context. In a fresh .Net 7 Blazor WASM Empty app it is. Looking into why...

**Comment by LostBeard** [comment]
Yup. If I switch the BlazorJSMSALTest project to .Net 7 it has the issue you are seeing. Narrowed it down a little bit...

**Comment by LostBeard** [comment]
It looks like the reason it works in .Net 8 and not .Net 7 is that appsettings loading was done differently in .Net 7 and was changed to the .Net 8 way after issue [#43700](https://github.com/dotnet/aspnetcore/issues/43700) was reported. Still trying to figure out a usable fix.

**Comment by LostBeard** [comment]
Fixed it! Required modifying the fetch calls from blazor.webassembly.js in web workers so that the urls are relative to the app base path, not the web worker's script path. 

Thank you so much for finding this issue and helping me resolve it. 

Updating the repo and building an updated Nuget release now.

**Comment by LostBeard** [comment]
Just ran your test app with WebWorkers 2.1.14 (Nuget is up) and it no longer has that issue. You may have to clear your browser cache to make sure it loads the updated web workers script.
