### ISSUE TITLE
StackOverflowException when calling my async method

### ISSUE THREAD

**Issue by ChaseFlorell** [LostBeard/SpawnDev.BlazorJS#8]
My Blazor WASM app is running on `net7.0`, and using this package

```xml
<PackageVersion Include="SpawnDev.BlazorJS.WebWorkers" Version="2.2.0" />
```

I'm getting the below exception when calling the following async method from within my ViewModel

```csharp
public async Task DownloadFile(Product product)
{
    using var _ = Busy();
    using var webWorker = await _webWorkerService.GetWebWorker() ?? throw new InvalidOperationException("Unable to find web worker");
    var exportService = webWorker.GetService<IProductExportService>();
    var result = await exportService.Export(product).ConfigureAwait(false);
    await _jsRuntime.InvokeVoidAsync("BlazorDownloadFile", result.Name, Convert.ToBase64String(result.Data)).ConfigureAwait(true);
}
```

<img width="1120" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/13711f56-7a8b-45b4-81f9-812cf0780bac">

I think I have my Program.cs setup correctly, so I'm at a loss as to what to do.

<img width="1008" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/1bd8eda3-3fb2-4866-bbba-4408828267c6">

**Comment by LostBeard** [comment]
Is the below line is failing? (The line that calls the IProductExportService.Export service method on the web worker.)
```cs
var result = await exportService.Export(product).ConfigureAwait(false);
```

I don't see the interface IProductExportService registered anywhere in your Program.cs.

Can you show the return type class for IProductExportService.Export please.

**Comment by ChaseFlorell** [comment]
<img width="1106" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/c15fe587-03bc-44aa-b961-e0c17ee2d07e">

<img width="537" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/892abb2b-0af4-49a9-8545-6610892eb0fb">

**Comment by LostBeard** [comment]
Where are you registering the service IProductExportService?

**Comment by ChaseFlorell** [comment]
sorry, all of my dependencies are being registered in DryIoC
<img width="800" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/e87b9451-d334-41fb-b03f-9d7c576d6121">

All of that setup happens in the Program.cs you see above

<img width="747" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/ad7fe861-3c7a-4d8c-96a5-48c7d6626be9">

**Comment by ChaseFlorell** [comment]
Interesting, I get a similar SOE with the update, and when I change the method to just return a primitive, I get this output.

<img width="1906" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/bec8a7d5-d87f-4f26-adf6-e94e45b1c4c6">

<img width="1161" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/98bc89e7-a90c-44d4-9f7e-e8ef5737f5a5">

<img width="521" alt="image" src="https://github.com/LostBeard/SpawnDev.BlazorJS/assets/471626/818afd1b-8c0b-4128-8104-5373bb1a5f93">

**Comment by LostBeard** [comment]
The "Service not registered" error is almost certainly due to the use of Dryloc (new to me.) To make WebWorkers compatible I will have to create a test project that uses Dryloc and tinker a bit. Then we can go from there.

**Comment by LostBeard** [comment]
What are the names and versions of the DryIoc package(s) you are using? I'm having a hard time finding examples that work in Blazor WASM.

**Comment by LostBeard** [comment]
I just tested a very simple WebWorkers project with DryIoc and it worked without issue. So that does not appear to be the problem unfortunately.

Where is that section called that registers those services (```// Services``` section)? If they are not registered before BlazorJSRunAsync is called they will not be available in a WebWorker.

I noticed in your last post your console output that showed the ```dotnet Loaded 18.93 MB resources``` from your main window and your web worker used different MB amounts (18.93 MB and 20.91 MB.) Slight chance your web worker and window loaded a different version of your app due to page caching or PWA code. 

Below is the basic DryIoc project Program.cs code I used for my test.

```cs
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");
            builder.RootComponents.Add<HeadOutlet>("head::after");

            builder.Services.AddBlazorJSRuntime();
            builder.Services.AddWebWorkerService();

            var useDryIoc = true;
            Console.WriteLine($"useDryIoc: {useDryIoc}");
            if (useDryIoc)
            {
                var container = new Container(Rules.Default.With(FactoryMethod.ConstructorWithResolvableArguments, propertiesAndFields: PropertiesAndFields.Auto).WithTrackingDisposableTransients());
                var diFactory = new DryIocServiceProviderFactory(container, RegistrySharing.Share);
                builder.ConfigureContainer(diFactory);
                container.Register<ITestService, TestService>(Reuse.Singleton);
            }
            else
            {
                builder.Services.AddSingleton<ITestService, TestService>();
            }

            var host = builder.Build();
            // make "_testWorker()" callable from the browser console
            BlazorJSRuntime.JS.Set("_testWorker", new ActionCallback(async () =>
            {
                var webWorkerService = host.Services.GetRequiredService<WebWorkerService>();
                using var worker = await webWorkerService.GetWebWorker();
                var workerTestService = worker.GetService<ITestService>();
                var ret = await workerTestService.TestMethod();
                BlazorJSRuntime.JS.Log(ret);
            }));
            await host.BlazorJSRunAsync();
        }
```

**Comment by LostBeard** [comment]
Sorry I have not been able to diagnose the issue you are having. I'm sure I can solve it if you can create a minimal project that can reproduce the issue.

**Comment by ChaseFlorell** [comment]
I am out of service for the weekend starting pretty soon, but I will try changing the order of operations on my container and see if that makes a difference. I will follow up next week, thank you for your help!

________________________________

**Comment by LostBeard** [comment]
Cannot reproduce.
